version: 2.1

jobs:
  unittest:
    parameters:
      python_version:
        description: Python version
        type: string
    environment:
      # The default machine (resource_class: medium) does not have enought memory
      CMAKE_BUILD_PARALLEL_LEVEL: "1"
      PYTHON_VERSION: << parameters.python_version >>
    docker:
      - image: "mthrok/tkaldi-test-base:py${PYTHON_VERSION}-0c6a3dcf0-2020-11-24"
    steps:
      - checkout
      - run:
          name: Setup Env
          command: .circleci/unittest/setup_env.sh
      - run:
          name: Build
          command: .circleci/unittest/build.sh
      - run:
          name: Run test
          command: .circleci/unittest/run_test.sh

workflows:
  unittest:
    jobs:
      - unittest:
          name: unittest_py3.6
          python_version: "3.6"
      - unittest:
          name: unittest_py3.7
          python_version: "3.7"
      - unittest:
          name: unittest_py3.8
          python_version: "3.8"
